### ISSUE TITLE
Login issues in Safari

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1234]
A few people were unable to log into Safari today on dev.nceas and test.arcticdata

**Comment by laurenwalker** [comment]
I was unable to reproduce this issue since Safari has been working fine for me. I'll keep the ticket open in case we keep seeing this issue.

**Comment by laurenwalker** [comment]
We ran into this issue again, and determined that Safari 12 has issues with third-party cookies using the `SameSite=None` property. (See https://bugs.webkit.org/show_bug.cgi?id=198181). Although this should not have been an issue when this ticket was originally filed since we only starting using the `SameSite` property ~February 1, 2020.

We implemented a fix for Safari 12 users, but have still seen issues with the cookies in Safari 13 sometimes. (It works for Rushiraj in MacOS Mojave but not Chris in MacOS Catalina). We still haven't found a fix for this, so will keep this ticket open.

Note: this isn't a MetacatUI issue per se, but I'll keep the issue here

**Comment by laijasmine** [comment]
This conversation came up again in response to a [ticket](https://support.nceas.ucsb.edu/rt/Ticket/Display.html?id=21095) in the Arctic Data Center. 

In release 2.10 notes it mentions [a troubleshooting option for Safari users](https://github.com/NCEAS/metacatui/releases/tag/2.10.0). However, when Amber tried those steps she still fails to login and has to switch to Chrome. I'm wondering if providing another suggestion of switching browsers might be also be helpful.

**Comment by amoeba** [comment]
Now that I look at our workaround for Safari users of having them allow third-party cookies browser-wide, I really don't like it since it exposes them to third-party cookies from other places around the web which is pretty harmful. Of course, unless they remember to re-enable the feature when they visit another site.

For datateam purposes, I think we need to simply be suggesting they use a browser which still allows third-party cookies by default. I say still because it looks like no major browser vendor will allow third-party cookies in the near future. For now, it appears Chrome and Firefox are fine alternatives, which means Edge should work too.

A larger fix is in the works to refactor how we do authentication should eventually get us around all of this.

**Comment by laurenwalker** [comment]
Agreed that a larger authentication refactor needs to happen to fix this. Everything else is just a bandaid on a slowly expanding wound

**Comment by mbjones** [comment]
The proposal is to refactor authentication in DataONE to [eliminate 3rd party cookies](https://github.com/DataONEorg/d1_portal/issues/12). Comments on that proposal welcomed.

**Comment by robyngit** [comment]
Note, to use keycloak in MetacatUI, we can use [keycloak-js](https://github.com/keycloak/keycloak-js). Docs are [here](https://www.keycloak.org/securing-apps/javascript-adapter)

**Comment by Br-Johnson** [comment]
I can reproduce this on the production KNB site using an iPhone with Safari, Chrome, and Firefox Focus. In each browser, ORCID authentication appears to complete successfully and returns me to KNB, but KNB still shows me as signed out.

This seems consistent with the third-party-cookie dependency described here: after returning from `/portal/oauth`, MetacatUI retrieves its DataONE token from the CN `/portal/token` endpoint using a credentialed cross-origin request.

I also reviewed DataONEorg/d1_portal#12 and the related Keycloak work. The Keycloak deployment and general OIDC support have progressed, but I couldn’t find a public MetacatUI PKCE implementation or a completed OIDC-to-DataONE token exchange.

Is there an active implementation branch or settled token-exchange contract for the remaining work? If so, I’d be interested in helping with a focused, test-backed contribution rather than duplicating the redesign.

**Comment by robyngit** [comment]
Hi @Br-Johnson! You're correct that the keycloak work is mostly complete on the back end, but not yet begun in MetacatUI. We're at the phase of determining if or how we will continue supporting JWT tokens during the transitional phase. We would absolutely welcome your contribution. When @mbjones is available, he would be able to provide more details.

**Comment by Br-Johnson** [comment]
Thanks @robyngit this is helpful. @mbjones, some broader context for why I’m interested:

I’m developing [metasalmon](https://github.com/salmon-data-mobilization/metasalmon), an R package for building and validating canonical [Salmon Data Packages](https://github.com/salmon-data-mobilization/smn-data-pkg), including semantic mappings to the Salmon Domain Ontology and export profiles for metadata catalogues.
The intended KNB workflow is to validate the package locally, generate EML and the DataONE/OAI-ORE aggregation, deposit a private version for review, and eventually publish it and request a DOI.

KNB is one publication profile; the same canonical package is intended to support DFO’s Enterprise Data Hub and other catalogue profiles without rebuilding the dataset differently for each destination.

Authentication therefore affects two related paths: authors and reviewers need reliable interactive access to private KNB records from desktop and mobile, while metasalmon needs a stable programmatic authentication contract for creating revisions and verifying them through the DataONE APIs. The current automation uses DataONE JWT bearer tokens, so the transitional decision you mentioned matters for more than the MetacatUI login screen.

Do you have a current view on which contract programmatic clients should target during the transition—continued DataONE JWTs, Keycloak access tokens accepted directly, or an OIDC-to-DataONE token exchange?

**Comment by mbjones** [comment]
This sounds great, @Br-Johnson and we would welcome contributions. 

As @robyngit said, we are in the middle of the transition, with the new Keycloak-based OIDC service operational, but some additional steps required to transition from D1Token to OIDC tokens. 

I track the work in this board: https://github.com/orgs/DataONEorg/projects/14/views/3

A general overview of the issues that we need to address are here: https://hpad.dataone.org/99HskvqWTbebCvvUxG-fYg?view

Let's touch base to talk about how to coordinate, and what path would be most expedient for your work. Several of the required items are close to complete, but the whole set will take a while.
